#automatic intervallization loop start .inc file
#Ben Waldecker Sep 2012

suffix parameter, IN;
suffix perturbed, IN;
suffix intervalID, IN;
suffix includeID, IN;

model parameterfree.mod;

include intervals.inc;

data parameterfree.dat;

option solver sipopt;
#option solver valipopt;

option sipopt_auxfiles rc;
#option valipopt_auxfiles rc;

include parameterresults.inc;
solve;

display time, xCU;